CREATE TABLE IF NOT EXISTS "foryou" (
	"id" serial PRIMARY KEY NOT NULL,
	"tmdb_id" integer NOT NULL,
	"imdb_id" text DEFAULT '',
	"title" text DEFAULT '',
	"name" text DEFAULT '',
	"overview" text DEFAULT '',
	"popularity" text DEFAULT '',
	"vote_average" integer DEFAULT 0,
	"vote_count" integer DEFAULT 0,
	"runtime" text DEFAULT '',
	"release_date" text DEFAULT '',
	"first_air_date" text DEFAULT '',
	"last_air_date" text DEFAULT '',
	"last_season" text DEFAULT '',
	"last_episode" text DEFAULT '',
	"genre1" text DEFAULT '',
	"genre2" text DEFAULT '',
	"genre3" text DEFAULT '',
	"poster_path" text DEFAULT '',
	"backdrop_path" text DEFAULT '',
	"logo_path" text DEFAULT '',
	"media_type" text DEFAULT ''
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "main" (
	"id" serial PRIMARY KEY NOT NULL,
	"tmdb_id" integer NOT NULL,
	"imdb_id" text DEFAULT '',
	"title" text DEFAULT '',
	"name" text DEFAULT '',
	"overview" text DEFAULT '',
	"popularity" text DEFAULT '',
	"vote_average" integer DEFAULT 0,
	"vote_count" integer DEFAULT 0,
	"runtime" text DEFAULT '',
	"release_date" text DEFAULT '',
	"first_air_date" text DEFAULT '',
	"last_air_date" text DEFAULT '',
	"last_season" text DEFAULT '',
	"last_episode" text DEFAULT '',
	"genre1" text DEFAULT '',
	"genre2" text DEFAULT '',
	"genre3" text DEFAULT '',
	"poster_path" text DEFAULT '',
	"backdrop_path" text DEFAULT '',
	"logo_path" text DEFAULT '',
	"media_type" text DEFAULT ''
);
